export const GET_ANNOUNCEMENT_LOADING = "GET_ANNOUNCEMENT_LOADING";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_ERROR = "GET_ANNOUNCEMENT_ERROR";
