export const GET_APPEALS_SUCCESS = "GET_APPEALS_SUCCESS";
export const GET_APPEALS_ERROR = "GET_APPEALS_ERROR";
export const ADD_APPEAL_SUCCESS = "ADD_APPEAL_SUCCESS";
export const UPDATE_APPEAL_SUCCESS = "UPDATE_APPEAL_SUCCESS";
export const DELETE_APPEAL_SUCCESS = "DELETE_APPEAL_SUCCESS";
export const GET_APPEALS_LOADING = "GET_APPEALS_LOADING";
