export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_PAGINATED_APPLICATIONS_SUCCESS =
  "GET_PAGINATED_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_ERROR = "GET_APPLICATIONS_ERROR";
export const ADD_APPLICATION_SUCCESS = "ADD_APPLICATION_SUCCESS";
export const UPDATE_APPLICATION_SUCCESS = "UPDATE_APPLICATION_SUCCESS";
export const DELETE_APPLICATION_SUCCESS = "DELETE_APPLICATION_SUCCESS";
export const GET_APPLICATIONS_LOADING = "GET_APPLICATIONS_LOADING";
export const GET_PAGINATED_APPLICATIONS_LOADING =
  "GET_PAGINATED_APPLICATIONS_LOADING";
export const GET_MY_APPLICATIONS_LOADING = "GET_MY_APPLICATIONS_LOADING";
export const GET_MY_APPLICATIONS_SUCCESS = "GET_MY_APPLICATIONS_SUCCESS";
export const GET_MY_APPLICATIONS_READY_FOR_CONTRACTS_SIGNING_SUCCESS =
  "GET_MY_APPLICATIONS_READY_FOR_CONTRACTS_SIGNING_SUCCESS";
export const GET_MY_APPLICATIONS_READY_FOR_MINUTES_NEGOTIATION_SUCCESS =
  "GET_MY_APPLICATIONS_READY_FOR_MINUTES_NEGOTIATION_SUCCESS";
export const GET_MY_APPLICATIONS_READY_FOR_CONTRACTS_SIGNING_LOADING =
  "GET_MY_APPLICATIONS_READY_FOR_CONTRACTS_SIGNING_LOADING";
export const GET_MY_APPLICATIONS_READY_FOR_MINUTES_NEGOTIATION_LOADING =
  "GET_MY_APPLICATIONS_READY_FOR_MINUTES_NEGOTIATION_LOADING";
export const GET_MY_APPLICATIONS_ERROR = "GET_MY_APPLICATIONS_ERROR";
