export const GET_APPLICANTS_SUCCESS = "GET_APPLICANTS_SUCCESS";
export const GET_APPLICANTS_ERROR = "GET_APPLICANTS_ERROR";
export const ADD_APPLICANT_SUCCESS = "ADD_APPLICANT_SUCCESS";
export const UPDATE_APPLICANT_SUCCESS = "UPDATE_APPLICANT_SUCCESS";
export const DELETE_APPLICANT_SUCCESS = "DELETE_APPLICANT_SUCCESS";
export const GET_APPLICANTS_LOADING = "GET_APPLICANTS_LOADING";
