export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_PERMISSIONS = "SET_PERMISSIONS";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_APPLICANT_PROFILE = "SET_APPLICANT_PROFILE";
export const SET_APPLICANT_ERROR = "SET_APPLICANT_ERROR";
