export const GET_BUDGET_LINES_SUCCESS = "GET_BUDGET_LINES_SUCCESS";
export const GET_SECTOR_BUDGET_LINES_SUCCESS =
  "GET_SECTOR_BUDGET_LINES_SUCCESS";
export const GET_BUDGET_LINES_ERROR = "GET_BUDGET_LINES_ERROR";
export const ADD_BUDGET_LINE_SUCCESS = "ADD_BUDGET_LINE_SUCCESS";
export const UPDATE_BUDGET_LINE_SUCCESS = "UPDATE_BUDGET_LINE_SUCCESS";
export const DELETE_BUDGET_LINE_SUCCESS = "DELETE_BUDGET_LINE_SUCCESS";
export const GET_BUDGET_LINES_LOADING = "GET_BUDGET_LINES_LOADING";
