export const GET_CALLS_SUCCESS = "GET_CALLS_SUCCESS";
export const GET_CALLS_ERROR = "GET_CALLS_ERROR";
export const ADD_CALL_SUCCESS = "ADD_CALL_SUCCESS";
export const UPDATE_CALL_SUCCESS = "UPDATE_CALL_SUCCESS";
export const DELETE_CALL_SUCCESS = "DELETE_CALL_SUCCESS";
export const GET_CALLS_LOADING = "GET_CALLS_LOADING";
