export const GET_COMPETENCE_SUCCESS = "GET_COMPETENCE_SUCCESS";
export const GET_COMPETENCE_ERROR = "GET_COMPETENCE_ERROR";
export const GET_COMPETENCE_LOADING = "GET_COMPETENCE_LOADING";

export const ADD_COMPETENCE_SUCCESS = "ADD_COMPETENCE_SUCCESS";
export const ADD_COMPETENCE_LOADING = "ADD_COMPETENCE_LOADING";
export const ADD_COMPETENCE_ERROR = "ADD_COMPETENCE_ERROR";

export const UPDATE_COMPETENCE_SUCCESS = "UPDATE_COMPETENCE_SUCCESS";
export const UPDATE_COMPETENCE_ERROR = "UPDATE_COMPETENCE_ERROR";
export const UPDATE_COMPETENCE_LOADING = "UPDATE_COMPETENCE_LOADING";

export const DELETE_COMPETENCE_SUCCESS = "DELETE_COMPETENCE_SUCCESS";
export const DELETE_COMPETENCE_ERROR = "DELETE_COMPETENCE_ERROR";
export const DELETE_COMPETENCE_LOADING = "DELETE_COMPETENCE_LOADING";

export const GET_COMPETENCE_BY_ID_SUCCESS = "GET_COMPETENCE_BY_ID_SUCCESS";
export const GET_COMPETENCE_BY_ID_ERROR = "GET_COMPETENCE_BY_ID_ERROR";
export const GET_COMPETENCE_BY_ID_LOADING = "GET_COMPETENCE_BY_ID_LOADING";
