export const GET_APPLICATIONS_BY_STAGE = "GET_APPLICATIONS_BY_STAGE";
export const GET_APPLICANTS_BY_STAGE = "GET_APPLICANTS_BY_STAGE";
export const GET_GENDER_COUNT_BY_STAGE = "GET_GENDER_COUNT_BY_STAGE";
export const GET_BUSINESS_TYPE_BY_STAGE = "GET_BUSINESS_TYPE_BY_STAGE";
export const GET_SUBMISSIONS_BY_SECTOR = "GET_SUBMISSIONS_BY_SECTOR";

export const SET_APPLICATIONS_BY_STAGE_LOADING =
  "SET_APPLICATIONS_BY_STAGE_LOADING";
export const SET_APPLICANTS_BY_STAGE_LOADING =
  "SET_APPLICANTS_BY_STAGE_LOADING";
export const SET_GENDER_COUNT_BY_STAGE_LOADING =
  "SET_GENDER_COUNT_BY_STAGE_LOADING";
export const SET_BUSINESS_TYPE_BY_STAGE_LOADING =
  "SET_BUSINESS_TYPE_BY_STAGE_LOADING";
export const SET_SUBMISSIONS_BY_SECTOR_LOADING =
  "SET_SUBMISSIONS_BY_SECTOR_LOADING";

export const SET_APPLICATIONS_BY_STAGE_ERROR =
  "SET_APPLICATIONS_BY_STAGE_ERROR";
export const SET_APPLICANTS_BY_STAGE_ERROR = "SET_APPLICANTS_BY_STAGE_ERROR";
export const SET_GENDER_COUNT_BY_STAGE_ERROR =
  "SET_GENDER_COUNT_BY_STAGE_ERROR";
export const SET_BUSINESS_TYPE_BY_STAGE_ERROR =
  "SET_BUSINESS_TYPE_BY_STAGE_ERROR";
export const SET_SUBMISSIONS_BY_SECTOR_ERROR =
  "SET_SUBMISSIONS_BY_SECTOR_ERROR";
