export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR";
export const GET_DASHBOARD_LOADING = "GET_DASHBOARD_LOADING";
export const GET_PRIORITY_SECTORS_DATA = "GET_PRIORITY_SECTORS_DATA";
