export const GET_STAGES_SUCCESS = "GET_STAGES_SUCCESS";
export const GET_STAGES_ERROR = "GET_STAGES_ERROR";
export const ADD_STAGE_SUCCESS = "ADD_STAGE_SUCCESS";
export const UPDATE_STAGE_SUCCESS = "UPDATE_STAGE_SUCCESS";
export const DELETE_STAGE_SUCCESS = "DELETE_STAGE_SUCCESS";
export const GET_STAGES_LOADING = "GET_STAGES_LOADING";
