export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_SECTOR_FORMS_SUCCESS = "GET_SECTOR_FORMS_SUCCESS";
export const GET_FORMS_ERROR = "GET_FORMS_ERROR";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
export const GET_FORMS_LOADING = "GET_FORMS_LOADING";

export const GET_SURVEYS_SUCCESS = "GET_SURVEYS_SUCCESS";
export const ADD_SURVEY_SUCCESS = "ADD_SURVEY_SUCCESS";
export const UPDATE_SURVEY_SUCCESS = "UPDATE_SURVEY_SUCCESS";
export const DELETE_SURVEY_SUCCESS = "DELETE_SURVEY_SUCCESS";
export const GET_SURVEYS_LOADING = "GET_SURVEYS_LOADING";
