export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_SECTOR_FORMS_SUCCESS = "GET_SECTOR_FORMS_SUCCESS";
export const GET_FORMS_ERROR = "GET_FORMS_ERROR";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
export const GET_FORMS_LOADING = "GET_FORMS_LOADING";
