export const GET_MEREPORTS_SUCCESS = "GET_MEREPORTS_SUCCESS";
export const GET_MEREPORTS_ERROR = "GET_MEREPORTS_ERROR";
export const ADD_MEREPORT_SUCCESS = "ADD_MEREPORT_SUCCESS";
export const UPDATE_MEREPORT_SUCCESS = "UPDATE_MEREPORT_SUCCESS";
export const DELETE_MEREPORT_SUCCESS = "DELETE_MEREPORT_SUCCESS";
export const GET_MEREPORTS_LOADING = "GET_MEREPORTS_LOADING";
