export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_APPLICANT_PROFILE_LOADING = "GET_APPLICANT_PROFILE_LOADING";
export const GET_APPLICANT_PROFILE_SUCCESS = "GET_APPLICANT_PROFILE_SUCCESS";
