export const GET_SECTORS_SUCCESS = "GET_SECTORS_SUCCESS";
export const GET_SECTORS_ERROR = "GET_SECTORS_ERROR";
export const ADD_SECTOR_SUCCESS = "ADD_SECTOR_SUCCESS";
export const ADD_TRADE_SECTOR_SUCCESS = "ADD_TRADE_SECTOR_SUCCESS";
export const UPDATE_SECTOR_SUCCESS = "UPDATE_SECTOR_SUCCESS";
export const DELETE_SECTOR_SUCCESS = "DELETE_SECTOR_SUCCESS";
export const GET_SECTORS_LOADING = "GET_SECTORS_LOADING";
