export const GET_SURVEY_TRAINEES_SUCCESS = "GET_SURVEY_TRAINEES_SUCCESS";
export const GET_SURVEY_TRAINEES_ERROR = "GET_SURVEY_TRAINEES_ERROR";
export const GET_SURVEY_TRAINEES_LOADING = "GET_SURVEY_TRAINEES_LOADING";
export const ADD_SURVEY_TRAINEE_SUCCESS = "ADD_SURVEY_TRAINEE_SUCCESS";
export const UPDATE_SURVEY_TRAINEE_SUCCESS = "UPDATE_SURVEY_TRAINEE_SUCCESS";
export const DELETE_SURVEY_TRAINEE_SUCCESS = "DELETE_SURVEY_TRAINEE_SUCCESS";
