export const GET_TRADES_SUCCESS = "GET_TRADES_SUCCESS";
export const GET_SECTOR_TRADES_SUCCESS = "GET_SECTOR_TRADES_SUCCESS";
export const GET_TRADES_ERROR = "GET_TRADES_ERROR";
export const GET_TRADES_LOADING = "GET_TRADES_LOADING";
export const ADD_TRADE_SUCCESS = "ADD_TRADE_SUCCESS";
export const UPDATE_TRADE_SUCCESS = "UPDATE_TRADE_SUCCESS";
export const DELETE_TRADE_SUCCESS = "DELETE_TRADE_SUCCESS";

