export const ADD_TRAINING_SUCCESS = "ADD_TRAINING_SUCCESS";
export const UPDATE_TRAINING_SUCCESS = "UPDATE_TRAINING_SUCCESS";

export const FETCH_TRAINING_BY_ID_REQUEST = "FETCH_TRAINING_BY_ID_REQUEST";
export const FETCH_TRAINING_BY_ID_SUCCESS = "FETCH_TRAINING_BY_ID_SUCCESS";
export const FETCH_TRAINING_BY_ID_FAILURE = "FETCH_TRAINING_BY_ID_FAILURE";

export const MAKE_DECISION_REQUEST = "MAKE_DECISION_REQUEST";
export const MAKE_DECISION_SUCCESS = "MAKE_DECISION_SUCCESS";
export const MAKE_DECISION_FAILURE = "MAKE_DECISION_FAILURE";

export const REQUEST_REVIEW_REQUEST = "REQUEST_REVIEW_REQUEST";
export const REQUEST_REVIEW_SUCCESS = "REQUEST_REVIEW_SUCCESS";
export const REQUEST_REVIEW_FAILURE = "REQUEST_REVIEW_FAILURE";

export const CERTIFICATION_REVIEW_REQUEST = "CERTIFICATION_REVIEW_REQUEST";
export const CERTIFICATION_REVIEW_SUCCESS = "CERTIFICATION_REVIEW_SUCCESS";
export const CERTIFICATION_REVIEW_FAILURE = "CERTIFICATION_REVIEW_FAILURE";

export const CERTIFICATION_DECISION_REQUEST = "CERTIFICATION_DECISION_REQUEST";
export const CERTIFICATION_DECISION_SUCCESS = "CERTIFICATION_DECISION_SUCCESS";
export const CERTIFICATION_DECISION_FAILURE = "CERTIFICATION_DECISION_FAILURE";

export const ADD_TRAINEE_REQUEST_REQUEST = "ADD_TRAINEE_REQUEST_REQUEST";
export const ADD_TRAINEE_REQUEST_SUCCESS = "ADD_TRAINEE_REQUEST_SUCCESS";
export const ADD_TRAINEE_REQUEST_FAILURE = "ADD_TRAINEE_REQUEST_FAILURE";

export const EDIT_TRAINEE_REQUEST_REQUEST = "EDIT_TRAINEE_REQUEST_REQUEST";
export const EDIT_TRAINEE_REQUEST_SUCCESS = "EDIT_TRAINEE_REQUEST_SUCCESS";
export const EDIT_TRAINEE_REQUEST_FAILURE = "EDIT_TRAINEE_REQUEST_FAILURE";

export const REMOVE_TRAINEE_REQUEST_REQUEST = "REMOVE_TRAINEE_REQUEST_REQUEST";
export const REMOVE_TRAINEE_REQUEST_SUCCESS = "REMOVE_TRAINEE_REQUEST_SUCCESS";
export const REMOVE_TRAINEE_REQUEST_FAILURE = "REMOVE_TRAINEE_REQUEST_FAILURE";

export const REQUEST_RESPONSE_REQUEST = "REQUEST_RESPONSE_REQUEST";
export const REQUEST_RESPONSE_SUCCESS = "REQUEST_RESPONSE_SUCCESS";
export const REQUEST_RESPONSE_FAILURE = "REQUEST_RESPONSE_FAILURE";

export const EDIT_TRAINEE_REQUEST = "EDIT_TRAINEE_REQUEST";
export const EDIT_TRAINEE_SUCCESS = "EDIT_TRAINEE_SUCCESS";
export const EDIT_TRAINEE_FAILURE = "EDIT_TRAINEE_FAILURE";

// Add trainees
export const ADD_TRAINEES_REQUEST = "ADD_TRAINEES_REQUEST";
export const ADD_TRAINEES_SUCCESS = "ADD_TRAINEES_SUCCESS";
export const ADD_TRAINEES_FAILURE = "ADD_TRAINEES_FAILURE";

// Remove trainee
export const REMOVE_TRAINEE_REQUEST = "REMOVE_TRAINEE_REQUEST";
export const REMOVE_TRAINEE_SUCCESS = "REMOVE_TRAINEE_SUCCESS";
export const REMOVE_TRAINEE_FAILURE = "REMOVE_TRAINEE_FAILURE";

//certified trainees
export const GET_CERTIFIED_TRAINEES_REQUEST = "GET_CERTIFIED_TRAINEES_REQUEST";
export const GET_CERTIFIED_TRAINEES_SUCCESS = "GET_CERTIFIED_TRAINEES_SUCCESS";
export const GET_CERTIFIED_TRAINEES_FAILURE = "GET_CERTIFIED_TRAINEES_FAILURE";

