export const ADD_TRAINING_SUCCESS = "ADD_TRAINING_SUCCESS";
export const UPDATE_TRAINING_SUCCESS = "UPDATE_TRAINING_SUCCESS";

export const FETCH_TRAINING_BY_ID_REQUEST = "FETCH_TRAINING_BY_ID_REQUEST";
export const FETCH_TRAINING_BY_ID_SUCCESS = "FETCH_TRAINING_BY_ID_SUCCESS";
export const FETCH_TRAINING_BY_ID_FAILURE = "FETCH_TRAINING_BY_ID_FAILURE";

export const MAKE_DECISION_REQUEST = "MAKE_DECISION_REQUEST";
export const MAKE_DECISION_SUCCESS = "MAKE_DECISION_SUCCESS";
export const MAKE_DECISION_FAILURE = "MAKE_DECISION_FAILURE";

export const REQUEST_REVIEW_REQUEST = "REQUEST_REVIEW_REQUEST";
export const REQUEST_REVIEW_SUCCESS = "REQUEST_REVIEW_SUCCESS";
export const REQUEST_REVIEW_FAILURE = "REQUEST_REVIEW_FAILURE";

export const CERTIFICATION_REVIEW_REQUEST = "CERTIFICATION_REVIEW_REQUEST";
export const CERTIFICATION_REVIEW_SUCCESS = "CERTIFICATION_REVIEW_SUCCESS";
export const CERTIFICATION_REVIEW_FAILURE = "CERTIFICATION_REVIEW_FAILURE";

export const CERTIFICATION_DECISION_REQUEST = "CERTIFICATION_DECISION_REQUEST";
export const CERTIFICATION_DECISION_SUCCESS = "CERTIFICATION_DECISION_SUCCESS";
export const CERTIFICATION_DECISION_FAILURE = "CERTIFICATION_DECISION_FAILURE";
