export const GET_WINDOWS_SUCCESS = "GET_WINDOWS_SUCCESS";
export const GET_WINDOWS_ERROR = "GET_WINDOWS_ERROR";
export const ADD_WINDOW_SUCCESS = "ADD_WINDOW_SUCCESS";
export const GET_WINDOWS_LOADING = "GET_WINDOWS_LOADING";
