name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: staging

      # Verify Current Directory
      - name: Verify Current Directory
        run: |
          echo "Current Directory: $(pwd)"
          ls -la ./staging

      # Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "Staging branch detected"
          chmod +x ./staging/scripts/create_staging_env.sh
          if [ ! -f ./staging/scripts/create_staging_env.sh ]; then
            echo "Script not found! Exiting."; exit 1;
          fi
          bash ./staging/scripts/create_staging_env.sh
          echo "FRONTEND_DIR=frontend-v2/staging" >> $GITHUB_ENV
          echo "PORT=5800" >> $GITHUB_ENV

      # Verify Git Status
      - name: Verify Git Status
        run: |
          cd staging
          git status

      # Install dependencies and build the application
      - name: Install dependencies and build the application
        run: |
          cd staging
          npm install --force
          npm run build
          
      # Start the application using pm2
      - name: Start the application using pm2
        run: |
          cd staging
          pm2 restart gms-frontend || pm2 start ecosystem.config.js --env .env.local
          pm2 save