name: Deploy Development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: dev

      # Set environment variables
      - name: Set Environment Variables
        run: |
          echo "Main branch detected"
          cd dev
          chmod +x ./scripts/create_dev_env.sh
          if [ ! -f ./scripts/create_dev_env.sh ]; then
            echo "create_dev_env.sh script not found! Exiting."; exit 1;
          fi
          bash ./scripts/create_dev_env.sh
          echo "FRONTEND_DIR=frontend-v2/dev" >> $GITHUB_ENV
          echo "PORT=5600" >> $GITHUB_ENV

      # Verify the current directory
      - name: Verify Current Directory
        run: |
          echo "Current Directory: $(pwd)"
          ls -la ./dev

      # Verify Git Status
      - name: Verify Git Status
        run: |
          cd dev
          git status

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('dev/package-lock.json', 'dev/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies and build the application
      - name: Install dependencies and build the application
        run: |
          cd dev
          npm install --force
          npm build

      # Install dependencies and build the application
      - name: Mode .next, package.json, node_modules folder to builds folder
        run: |
          cd dev
          cp -r .next ~/frontend-actions-runner/_work/frontend-v2/frontend-v2/builds/dev/
          cp -r package.json ~/frontend-actions-runner/_work/frontend-v2/frontend-v2/builds/dev/
          cp -r node_modules ~/frontend-actions-runner/_work/frontend-v2/frontend-v2/builds/dev/
      # Start the application using pm2
      - name: Start the application using pm2
        run: |

          cd ~/frontend-actions-runner/_work/frontend-v2/frontend-v2/builds/dev/
          pm2 restart gms-dev || pm2 start ecosystem.config.js
          pm2 save
