name: Deploy To Testing Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Node.js v20 is installed
        run: |
          node_version=$(node -v)
          echo "Current Node.js version: $node_version"

          if [[ "$node_version" != "v20"* ]]; then
            echo "Installing Node.js v20..."
            # Install Node.js v20 using n
            curl -L https://git.io/n-install | bash
            export N_PREFIX=$HOME/n
            export PATH=$N_PREFIX/bin:$PATH
            n 20
          fi

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Install dependencies
        run: npm ci
        working-directory: ~/apps/staging/frontend-v2-staging

      - name: Create environment variables
        run: |
          chmod +x scripts/create_staging_env.sh
          ./scripts/create_staging_env.sh

      - name: Build Next.js app
        run: npm run build
        working-directory: ~/apps/staging/frontend-v2-staging

      - name: Deploy Application
        if: success()
        run: |
          cd ~/apps/staging/frontend-v2-staging
          git fetch origin
          git reset --hard origin/staging  # Ensure the latest code is fetched and checked out
          pm2 restart gms-staging
          pm2 save

      - name: Check if pm2 is running
        run: pm2 list

      - name: Notify failure on Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: failure
          message: 'Deployment to staging failed!'
