name: Deploy Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set environment variables based on the branch (Main or Staging)
      - name: Set Environment Variables 
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "Main branch detected"
            cp ./.env.main ./.env # For main branch
            export FRONTEND_DIR=frontend-v2
            export PORT=5600
          elif [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            echo "Staging branch detected"
            cp ./.env.staging ./.env # For staging branch
            export FRONTEND_DIR=frontend-v2-staging
            export PORT=5800
          fi
          echo "FRONTEND_DIR=$FRONTEND_DIR"
          echo "PORT=$PORT"

      # Verify Current Directory
      - name: Verify Current Directory
        run: |
          echo "Current Directory: $(pwd)"
          ls -la
          if [ ! -d ".git" ]; then
            echo "No .git directory found. This is unexpected."
          fi

      # Verify Git Status
      - name: Verify Git Status
        run: |
          cd ~/apps/$FRONTEND_DIR
          git status

      # Install dependencies and build the application
      - name: Install dependencies and build the application
        run: |
          cd ~/apps/$FRONTEND_DIR
          git pull origin $GITHUB_REF
          npm install --force
          npm run build

      # Start the application using pm2
      - name: Start the application using pm2
        run: |
          cd ~/apps/$FRONTEND_DIR
          pm2 stop $FRONTEND_DIR || true  # Stop any running instance (if exists)
          pm2 start npm --name $FRONTEND_DIR -- run start -- --port $PORT
          pm2 save
